### PR TITLE
Global side nav (experimental)

### LINKED ISSUE #1810: Global side-nav (experimental)
Root nodes should get an additional flag to be displayed not in top nav area but in a global side-nav area.

This feature should be marked as experimental, since Design specs are not finalized yet

TBD:
* mobile behaviour
* styling/theming variables to be used

out of scope for this issue:

* general feature set of this global side nav (badge counter? dropdowns? etc.)

### PR DESCRIPTION
**Pull request by stanleychh**
`Fixes #1810 `

### CODE REVIEW

**Comment by JohannesDoberer** [comment]
I get some overlapping misbehaviour ( I guess)
When I have configured a tab nav in combination of global nav I will get some overlapping when expand or collapse the navigation.
Bildschirmfoto 2021-03-11 um 13 49 42
Bildschirmfoto 2021-03-11 um 13 49 52

**Comment by JohannesDoberer** [comment]
If global nav is activated and we don't have any node in the top nav we should not render the `three dots` in mobile view.

**Comment by JohannesDoberer** [comment]
Setup: mobile view, `responsiveNavigation: 'simple'`
Can't see the content, because left nav don't disappear.

**Comment by stanleychh** [comment]
Thanks @JohannesDoberer . I have fixed those issues you found out, Please have a look again.

**Review by JohannesDoberer — APPROVED** [review]
Good Job!

**Comment by JohannesDoberer** [comment]
Although it is experimental we need some docu and tests. It is fine for me in a follow-up ticket as well.

**Pull request merged**
