### PR TITLE
Luigi container and Compound Container API docs update

### PR DESCRIPTION
**Pull request by smahati**
**Description**

Changes proposed in this pull request:

- Cosmetic changes to the documentation

### CODE REVIEW

**Review by ndricimrr — CHANGES_REQUESTED** [review]
This particular markdown file is not to be manually edited. 

We document new features/functions with **JSDoc** comment header descriptions and then use  our custom made scripts to generate and keep that in sync with the respective .md files. 
(Some .md files which don't relate to function descriptions, like tutorials, examples, guides, faq etc, are of course manually edited in the /docs folder where all .md files reside.)

In this case we only update the respective **JSDoc** Comments , so you should make your suggested changes instead on the in-code **JSDOC** instead : https://github.com/SAP/luigi/blob/main/container/typings/LuigiCompoundContainer.svelte.d.ts

Afterwards update the markdown file using the documentation script:
```
cd script
npm run docu
```
This should then also do an update to the .md files. 

Afterwards just commit the result.

**Review by ndricimrr — COMMENTED** [review]
We have no strict rules regarding PR title names, but try to keep a concise description of what the PR does. 
This makes it much easier when going back in Commit history of the main branch as to what each PR did.

**Review by smahati — COMMENTED** [review]
updated the jsdoc comments :)

**Review by ndricimrr — APPROVED** [review]
Looks good 👍 . I put it into To Accept column. When its ready to merge I will notify you.

**Comment by ndricimrr** [comment]
You may merge now @smahati ✅

**Pull request merged**
