### PR TITLE
Update navigation-parameters-reference doc with Promise children nodes

### LINKED ISSUE #3667: children property returns a promise
Add documentation that [children](https://docs.luigi-project.io/docs/navigation-parameters-reference/?section=children) property can also return a promise like:

```
children:  () => {
       return new Promise((resolve, reject) => {
             fetch('/noed/endpoint').then((...)=>{
               ...
               resolve(nodes);
             });
       })
}
```

### PR DESCRIPTION
**Pull request by Jotrorox**
I only updated the Docs, but please still read the description even though this being a ~20 LOC change.

**Description**

Hey it's me again, I just wanted to say it's the same as always I'm new to all of this and if anything is wrong with it please just tell me. If you want or need to contact me, just do so under mail@jotrorox.com.

Best Regards 
Johannes 

Changes proposed in this pull request:
- Updating the description and example for the children parameter on the navigation

**Related issue(s)**
Should resolve #3667

### CODE REVIEW

**Review by JohannesDoberer — APPROVED** [review]

**Comment by Jotrorox** [comment]
Hey,
Sorry for the comment, but I'm panicking really hard right now, since after my pr got merged the test login-flow-nav-dropdown test failed even though my changes didn't (at least to my understanding) change anything that could've allowed the tests to fail. Also, the tests pre merge didn't fail. So either I'm missing something or there is an error somewhere else, which I don't see either. I'd be happy about a response. And again, sorry for the comment and all the fuss.

Kind Regards
Johannes

**Comment by JohannesDoberer** [comment]
Hey @Jotrorox,
merged another pr and backwards compatibility tests are green. If it will happen more frequently we will investigate this kind of flaky test.
So.. all good and thx for your contribution :)

**Comment by Jotrorox** [comment]
Hey @JohannesDoberer,
Thanks for the quick response and if it all seems to work now I can calm down.
Btw. since SAP is a German company and all the maintainers of this project seem to be located in Germany as well, is it allowed to write pull requests in German?

Best Regards 
Johannes

**Comment by JohannesDoberer** [comment]
Hey @Jotrorox,
in theory you are right to write PR's in German, but there are reasons against it.
We have team members who are not native German speakers. Another reason is that we are an open source project and not every user/contributor in our community understands the German language as well.

Cheers,
Johannes

**Pull request merged**
