### PR TITLE
Update devDependencies of Docs

### PR DESCRIPTION
**Pull request by stanleychh**
Security alerts for docs example: https://github.com/SAP/luigi/security/dependabot

- Upgrade version of copy-webpack-plugin & mini-css-extract-plugin
- remove unnecessary dependencies

### CODE REVIEW

**Review by JohannesDoberer — COMMENTED** [review]
Bildschirmfoto 2021-06-15 um 21 07 11
Can't start our docs anymore.

**Review by UlianaMunich — APPROVED** [review]

**Comment by ndricimrr** [comment]
I'm also unable to start docs too. 

What I did. 

1. Pull branch
2. Run `lerna clean` to delete all node_modules everywhere.
3. Go into website/docs
4. Run `npm install`
5. Run `npm start`

I get the following:

Screen Shot 2021-06-16 at 16 34 05

**Comment by stanleychh** [comment]
@ndricimrr thanks for reviewing.
It is strange. I also followed your steps above, and it works perfectly.
Also, I have the same `node` and `npm` version as you.

**Comment by stanleychh** [comment]
@JohannesDoberer @ndricimrr , would you mind giving a try that reinstall "rehype-parse": "^6.0.1"  https://github.com/SAP/luigi/pull/2093/files#diff-f8163f8a9f10a5bf4fc5f45f1b45277ab361ff6586f4503767abd71a2294ca60L56 ?  See if it works.
I've checked `generate-docu-sitemap.js` which might relate to parsing functionalities, but 100% not sure.

**Comment by JohannesDoberer** [comment]
Doesn't help.. still failing.
I found a solution how we can go with the removed and updated dependencies.
We have to switch the command of *build:config* in package.json
```
"build:config": "node -r esm scripts/generate-docu-sitemap.js && webpack --config webpack-generateConfig.config",
```
First we generate the sitemap and than do the webpack stuff (which also includes copying of the sitemap).

**Pull request merged**
