### PR TITLE
Update user settings dialog HTML layout

### LINKED ISSUE #1881: Refactor UserSettingsEditor.html according to FD Styles grid for forms
It would be great to re-use as much classes as possible from FD Styles and as less a s possible custom internal classes

https://sap.github.io/fundamental-styles/?path=/docs/components-forms-form-grid--s-size

### PR DESCRIPTION
**Pull request by UlianaMunich**
Fixes #1881

### CODE REVIEW

**Review by stanleychh — APPROVED** [review]

**Review by legteodav — APPROVED** [review]
just running the branch locally and looks good ....

**Comment by UlianaMunich** [comment]
Ticket is on hold, due to clarification of Mobile view for Forms fields. 
Should we use vertical or horizontal is not yet defined: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2104441836 and related to label concatenation on mobile

**Comment by JohannesDoberer** [comment]
When I have a not editable value it is wrong formatted. 
Bildschirmfoto 2021-04-22 um 15 18 49

**Review by JohannesDoberer — APPROVED** [review]
LGTM! 👍

**Pull request merged**
