### PR TITLE
Website security

### LINKED ISSUE #1735: Improve security for website
Currently we have a _blank target vulnerability for some links on our website.

How to fix:
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
https://perishablepress.com/fix-blank-target-vulnerability/

### PR DESCRIPTION
**Pull request by JohannesDoberer**
Important note: `rel` attribute has to be in the same line as the `target`attribute.
Fixes #1735

### CODE REVIEW

**Review by UlianaMunich — CHANGES_REQUESTED** [review]
- All the links are updated except for those which are for Blog posts. They are coming from the docu and compiled automatically, so you would need to modify the template.

- And not related to this ticket a small bug: The link "Get started" which guides to the Docu doesn't work `"https://docs.luigi-project.io/docs/application-setup.md` could you please simply delete the *.md extensions from it so that it is fixed?

**Comment by JohannesDoberer** [comment]
> All the links are updated except for those which are for Blog posts. They are coming from the docu and compiled automatically, so you would need to modify the template.
Did you build the blogs? It is fixed in `global-nav.html` template.

The small bug is fixed.

**Review by UlianaMunich — APPROVED** [review]
LGTM!

**Review by ndricimrr — APPROVED** [review]
Looks good 👍

**Pull request merged**
