### PR TITLE
Fix shellbar buttons alignment issue

### LINKED ISSUE #1604: Shellbar buttons are not aligned
The shellbar buttons are not aligned.

### PR DESCRIPTION
**Pull request by stanleychh**
Fixes #1604 

shellbar-button

### CODE REVIEW

**Review by ndricimrr — COMMENTED** [review]
same as @UlianaMunich , couldn't manage to reproduce it in my machine 🤔

**Comment by stanleychh** [comment]
@hardl, thanks for your time investigating this issue. I have pushed a fix of removing line height.

**Comment by hardl** [comment]
turns out that this issue is caused by 
```
.fd-shellbar__button .fd-top-nav__icon {
line-height: 2.4rem;
...
```

which is also responsible for additional misalignment.

Please revert 
margin-top: 10px;

and remove line-height

**Review by JohannesDoberer — APPROVED** [review]
👍

**Review by ndricimrr — APPROVED** [review]
👍

**Pull request merged**
