### PR TITLE
Fix path routing

### PR DESCRIPTION
**Pull request by y-kkamil**
**Description**

Changes proposed in this pull request:

- Fixes the problem with reloaded micro frontend view when using path routing

**Related issue(s)**

https://github.com/kyma-project/console/issues/798, which includes the steps to reproduce the issue.

### CODE REVIEW

**Comment by y-kkamil** [comment]
Fixes #491

**Comment by y-kkamil** [comment]
Checked for angular/vue/react routers. Please test for any use case you can think of. ;)
Unfortunately, https://github.com/kyma-project/console/issues/798 still persists.

**Comment by jesusreal** [comment]
This ticket is still blocked until https://github.com/kyma-project/console/issues/798  is solved.

**Comment by y-kkamil** [comment]
react-router uses a library called [history](https://github.com/ReactTraining/history/) internally. https://github.com/ReactTraining/history/blob/master/modules/DOMUtils.js#L53 --> this is the line that was causing problems for console. Adding state to `PopStateEvent` makes the expression evaluate to false, which in turn let's the router take care of route change.

**Pull request merged**
