### PR TITLE
Fix `withoutSync()` history behaviour

### LINKED ISSUE #1719: withoutsync should use history replaceState instead of pushstate
... to avoid erroneous browser back behaviour.

**Current Situation** (Assumption, double-check):
* when there is a route change within a micro frontend iframe induced by a location change, a new state is added to the browser history.
* if the micro frontend is now sending a linkmanager.withoutsync.navigate to luigi core, luigi also add a new state to browser history.
* if you click on browser back button now, you end in an inconsistent "half-"state, so you have to press back twice to go to previous state and active node indication is out of sync in between.

### PR DESCRIPTION
**Pull request by andrei-scripcaru**
**Description**

Changes proposed in this pull request:

- `.withoutSync()` should use history `replaceState` instead of `pushState`

Automatically formatted by Prettier via Husky. Relevant line: `286`.

**Related issue(s)**
Fixes #1719

### CODE REVIEW

**Comment by andrei-scripcaru** [comment]
Based on my understanding, the following change should be enough to close #1719, but please correct me if I'm wrong.

> `Routing.navigateTo(path);`
> `Routing.navigateTo(path, isNavigationSyncEnabled);`

**Comment by andrei-scripcaru** [comment]
@hardl Hey! Is there a reason for Travis CI pipeline not to run on this PR?

**Comment by hardl** [comment]
> @hardl Hey! Is there a reason for Travis CI pipeline not to run on this PR?

was just in the queue ;)

**Review by maxmarkus — APPROVED** [review]
LGTM 👍 and since there is a separate ticket for the according e2e test, I accept this one.

**Review by JohannesDoberer — APPROVED** [review]

**Pull request merged**
