### PR TITLE
feature/expose-login-method

### PR DESCRIPTION
**Pull request by ionutcirja**
**Description**

Changes proposed in this pull request:

- expose login method

### CODE REVIEW

**Comment by alexandra-simeonova** [comment]
Thank you for your contribution! 🚀 
A friendly tip: because API documentation is [different](https://github.com/SAP/luigi/blob/f8e93ba40d128d80d192379801d3512ba8b7507b/docs/content-guidelines.md#api-documentation) from other documentation in Luigi (it is automatically generated), we'd like to ask you to run `lerna run docu` from the root Luigi folder. (If you didn't install Lerna yet, look [here](https://github.com/SAP/luigi/blob/c8ea8d4b5d2d9752d4c8548330b387f59c93d047/core/README.md#link-and-build-with-lerna).) This should then generate the documentation.

**Review by alexandra-simeonova — APPROVED** [review]

**Comment by ionutcirja** [comment]
Hello guys, do you have any idea how soon can you merge this? Thanks.

**Comment by maxmarkus** [comment]
Hello @ionutcirja 

I have checked your PR and it is working. Since I would like to see the the stuff tested, I have created the e2e test for you. 
Would you please add it to `fiddle-navigation.spec.js:338` after the `No profile, logged in`test? 

```javascript

      it('Trigger Login and Logout with Core API', () => {
        newConfig.navigation.profile = undefined;
        newConfig.auth.disableAutoLogin = true;
        visitWithAuthConfig('/', newConfig);

        cy.get('[data-testid="luigi-topnav-profile"] button').click();
        loginLink().should('exist');

        cy.window().then(win => {
          cy.log('Trigger auth().login()');
          win.Luigi.auth().login();
        });

        cy.login('tets@email.com', 'tets', true);

        cy.get('[data-testid="luigi-topnav-profile"] button').click();
        logoutLink().should('exist');

        cy.window().then(win => {
          cy.log('Trigger auth().logout()');
          win.Luigi.auth().logout();
        });

        cy.contains('Login again');
      });
```

**Review by maxmarkus — APPROVED** [review]
LGTM. Thanks! 👍

**Review by JohannesDoberer — APPROVED** [review]

**Comment by maxmarkus** [comment]
> Thank you for your contribution! 🚀
> A friendly tip: because API documentation is [different](https://github.com/SAP/luigi/blob/f8e93ba40d128d80d192379801d3512ba8b7507b/docs/content-guidelines.md#api-documentation) from other documentation in Luigi (it is automatically generated), we'd like to ask you to run `lerna run docu` from the root Luigi folder. (If you didn't install Lerna yet, look [here](https://github.com/SAP/luigi/blob/c8ea8d4b5d2d9752d4c8548330b387f59c93d047/core/README.md#link-and-build-with-lerna).) This should then generate the documentation.

I guess a missing `npm install` in the root folder is the root-cause, it would install the pre-commit and pre-push hooks that do the job. @ionutcirja be sure to run `npm install` in the main repo folder to be safe for the future.

**Review by ndricimrr — APPROVED** [review]

**Pull request merged**
